### ISSUE TITLE
0.0.27: Main menu (text menu) disappeared

### ISSUE THREAD

**Issue by sfrsfrsfr** [Portree-Kid/flightgear-airports#111]
somehow i managed to make the main text menu (File...) disappear, even after restarting fga.
[screenshot](https://www.imgpaste.net/image/UbS5b) showing the issue.

**Comment by wkitty42** [comment]
even if you click on the hamburger in the top left?

**Comment by sfrsfrsfr** [comment]
the thingy with the three lines? that only enlarges/shrinks the white rectangle around the hamburger.

**Comment by wkitty42** [comment]
On 1/5/21 9:28 AM, sfrsfrsfr wrote:
> the thingy with the three lines? that only enlarges/shrinks the white rectangle 
> around the hamburger.

can you post an image, please? it seems to work here...

i've tested with versions 0.0.20 thru 0.0.27... when you click on the hamburger, 
the entire menu box opens by expanding to the right... once open, the help text 
shows... closing it and clicking on any other option also opens the entire menu 
box in the same manner with those options being available...

my testing machine is an old kubuntu 14.04... i'm using the appimages...

**Comment by sfrsfrsfr** [comment]
@wkitty42 regarding the image pls check the link in my first post :)

to clarify: i'm referring to the text menu with the 'File Edit View Window Help' options in it.
In 0.0.26 they are shown just fine. But not in 0.0.27. Iirc this menu was shown initially in 0.0.27 but somehow has disappeared.

i'm on Kubuntu 18.04 also using the appimage.

**Comment by wkitty42** [comment]
On 1/5/21 12:03 PM, sfrsfrsfr wrote:
> @wkitty42 regarding the image pls check the link in my first post :)

i did check that image before my first response... in fact, checking that image 
is exactly what caused me to point out clicking on the hamburger... it looks 
like a normal closed menu bar... not an all white with no text expanded one as i 
seem to recall being mentioned...

> to clarify: i'm referring to the text menu with the 'File Edit View Window Help' 
> options in it.

wait, what???

> In 0.0.26 they are shown just fine. But not in 0.0.27. Iirc this menu was shown 
> initially in 0.0.27 but somehow has disappeared.

OOOHHHHH!!!!! i thought you were talking about the vertical bar menu on the 
left... yeah, the horizontal one above the application work area is completely 
gone in 0.0.27... i don't know that it ever really did anything that wasn't 
already done in the other menus in the app... i didn't even notice they were 
gone since i never used or needed them... i don't even see those on my other 
apps unless i specifically turn them on if they even have the option for them...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by Portree-Kid** [comment]
Intentional. It's just a debug menu and does nothing for the application

**Comment by sfrsfrsfr** [comment]
ok, no big deal :)
